const fs = require('fs');
const path = require('path');

const TILES_DIR = path.join(__dirname, '..', 'riichienv-mahjong-tiles-regular');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'tiles.ts');

if (!fs.existsSync(TILES_DIR)) {
    console.error(`Error: Tiles directory not found at ${TILES_DIR}`);
    console.error("Please ensure the 'riichienv-mahjong-tiles-regular' directory exists in the project root.");
    process.exit(1);
}

const mapFileNameToId = (filename) => {
    const name = path.basename(filename, '.svg');

    if (name === 'Back') return 'back';
    if (name === 'Blank') return 'blank';
    if (name === 'Front') return 'front';

    const suits = { 'Man': 'm', 'Pin': 'p', 'Sou': 's' };

    for (const [prefix, suffix] of Object.entries(suits)) {
        if (name.startsWith(prefix)) {
            const rest = name.slice(prefix.length);
            if (rest.includes('-Dora')) {
                return '5' + suffix + 'r';
            }
            return rest + suffix;
        }
    }

    const honors = {
        'Ton': 'E', 'Nan': 'S', 'Shaa': 'W', 'Pei': 'N',
        'Haku': 'P', 'Hatsu': 'F', 'Chun': 'C'
    };

    if (honors[name]) {
        return honors[name];
    }

    return null;
};

/**
 * Clean SVG content for embedding.
 * Removes Inkscape/Sodipodi editor artifacts while preserving
 * browser-renderable elements (gradients, clip paths, masks, etc.).
 */
const cleanSvg = (content) => {
    // Ensure xlink namespace if needed
    if (content.includes('xlink:href') && !content.includes('xmlns:xlink')) {
        content = content.replace('<svg', '<svg xmlns:xlink="http://www.w3.org/1999/xlink"');
    }

    // 1. Remove XML declaration and comments
    content = content.replace(/<\?xml.*?\?>/gs, '');
    content = content.replace(/<!--.*?-->/gs, '');

    // 2. Remove metadata, namedview, RDF
    content = content.replace(/<metadata.*?>.*?<\/metadata>/gs, '');
    content = content.replace(/<sodipodi:namedview.*?>.*?<\/sodipodi:namedview>/gs, '');
    content = content.replace(/<rdf:RDF.*?>.*?<\/rdf:RDF>/gs, '');

    // 3. Remove inkscape:path-effect elements (not rendered by browsers)
    content = content.replace(/<inkscape:path-effect[^>]*\/?>/g, '');

    // 4. Remove namespaced attributes (Inkscape, Sodipodi, etc.) but keep xlink:href, xmlns:xlink, and viewBox
    content = content.replace(/\s\w+:[^=]+="[^"]*"/g, (match) => {
        if (match.includes('xlink:href')) return match;
        if (match.includes('xmlns:xlink')) return match;
        if (match.includes('viewBox')) return match;
        return '';
    });

    // 5. Remove explicit width/height to allow CSS scaling
    content = content.replace(/<svg\s+([^>]*?)width="[^"]*"/g, '<svg $1');
    content = content.replace(/<svg\s+([^>]*?)height="[^"]*"/g, '<svg $1');

    // 6. Remove unreferenced id attributes
    //    Collect all ids and all references (url(#...) and xlink:href="#...")
    const idMatches = [...content.matchAll(/\sid="([^"]+)"/g)];
    const urlRefs = [...content.matchAll(/url\(#([^)]+)\)/g)].map(m => m[1]);
    const xlinkRefs = [...content.matchAll(/xlink:href="#([^"]+)"/g)].map(m => m[1]);
    const refSet = new Set([...urlRefs, ...xlinkRefs]);

    for (const m of idMatches) {
        if (!refSet.has(m[1])) {
            content = content.replace(m[0], '');
        }
    }

    // 7. Remove xmlns:inkscape and xmlns:sodipodi namespace declarations
    content = content.replace(/\s*xmlns:inkscape="[^"]*"/g, '');
    content = content.replace(/\s*xmlns:sodipodi="[^"]*"/g, '');
    content = content.replace(/\s*xmlns:rdf="[^"]*"/g, '');
    content = content.replace(/\s*xmlns:cc="[^"]*"/g, '');
    content = content.replace(/\s*xmlns:dc="[^"]*"/g, '');

    // 8. Remove version attribute from <svg>
    content = content.replace(/(<svg[^>]*?)\s+version="[^"]*"/g, '$1');

    // 9. Collapse whitespace
    content = content.replace(/\s+/g, ' ').trim();

    return content;
};

const main = () => {
    const files = fs.readdirSync(TILES_DIR).filter(f => f.endsWith('.svg'));
    const tileMap = {};

    let originalSize = 0;
    let cleanedSize = 0;

    files.forEach(file => {
        const id = mapFileNameToId(file);
        if (id) {
            const raw = fs.readFileSync(path.join(TILES_DIR, file), 'utf8');
            originalSize += raw.length;

            const content = cleanSvg(raw);
            if (content) {
                tileMap[id] = content;
                cleanedSize += content.length;
            }
        }
    });

    // Alias 0m/0p/0s to red tiles — emit as runtime references, not data copies
    const aliases = [];
    if (tileMap['5mr']) aliases.push(['0m', '5mr']);
    if (tileMap['5pr']) aliases.push(['0p', '5pr']);
    if (tileMap['5sr']) aliases.push(['0s', '5sr']);

    // Build output: base tile data + alias assignments
    let outputContent = `// Auto-generated by scripts/gen_tiles.js\n`;
    outputContent += `export const TILES: Record<string, string> = ${JSON.stringify(tileMap)};\n`;
    for (const [alias, target] of aliases) {
        outputContent += `TILES['${alias}'] = TILES['${target}'];\n`;
    }

    fs.writeFileSync(OUTPUT_FILE, outputContent);

    const savings = originalSize - cleanedSize;
    console.log(`Generated ${OUTPUT_FILE} with ${Object.keys(tileMap).length} tiles (+${aliases.length} aliases).`);
    console.log(`SVG data: ${(cleanedSize / 1024).toFixed(1)} KB (saved ${(savings / 1024).toFixed(1)} KB from source)`);
};

main();
